//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int itemId { get; set; }
        public Nullable<int> itemSet { get; set; }
        public string itemName { get; set; }
    
        public virtual Subcategory Subcategory { get; set; }
    }
}
