//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazalar
    {
        public int StoreId { get; set; }
        public Nullable<int> StoreSet { get; set; }
        public Nullable<int> StoreCode { get; set; }
        public string StoreName { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DateCreated { get; set; }
    
        public virtual Markalar Markalar { get; set; }
    }
}
