//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceForms
    {
        public int Id { get; set; }
        public string HelpdeskId { get; set; }
        public string IncNumber { get; set; }
        public string ServiceType { get; set; }
        public string Site { get; set; }
        public string StoreSelect { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
        public string Items { get; set; }
        public string VendorSR { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public string Technician { get; set; }
        public string SignatureData { get; set; }
        public string SupportPersonName { get; set; }
        public string FormDetails { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> Durum { get; set; }
        public string TechnicianSignatureFileName { get; set; }
        public string Adress { get; set; }
        public string CityDistrict { get; set; }
    }
}
